(ns nl-injector)
 ;can take this in as a vector, NOT a map. Remove dupes and then put it INTO a map.

(def multi-fl '#{
                  (adjacent (bay 3) (forklift 1))
                  (adjacent (bay 4) (forklift 2))
                  (isa bay (bay 3))
                  (isa bay (bay 4))
                  (isa forklift 1); multi forklifts issue here
                  (isa forklift 2)
                  (isa loading-bay (bay 5))
                  (isa bay (bay 5))
                  (isa bay (bay 1))
                  (isa bay (bay 2))
                  (on (bay 1) (shelf 1))
                  (on (bay 2) (shelf 2))

                  (holds (shelf 1) (object 1))
                  (holds (shelf 2) (object 2))
                  (holds (shelf 1) (object 2))
                  (holds (shelf 2) (object 1))
                  (holds (forklift 1) none)
                  (holds (forklift 2) none)


                  })

(def mock-comb    '#{(adjacent (bay 1) (forklift 1))
                    (isa bay (bay 2))
                    (holds (forklift 1) none)
                    (holds (shelf 1) (nails-crate 1))
                    (isa loading-bay (bay 3))
                     (isa bay (bay3))
                    })



(def mock-dyn2 '#{
                         (stored-on (shelf 194) wheels-crate 240)
                         (on (6 0) (forklift 324))
                         (isa forklift (forklift 324))
                         (is-height 0 (forklift 324))
                         })

(def dyn-sample '#{(holds (bay 11) (nails-crate 86))
           (holds (shelf 36) (pistons-crate 112))
           (holds (bay 11) (circular-saws-crate 84))
           (holds (bay 4) (engines-crate 121))
           (holds (shelf 60) (pistons-crate 107))
           (holds (bay 12) (wheels-crate 104))
           (holds (shelf 35) (screws-crate 97))
           (holds (shelf 66) (screws-crate 96))
           (holds (shelf 39) (wheels-crate 104))
           (holds (bay 10) (tyres-crate 116))
           (holds (shelf 21) (compressors-crate 109))
           (holds (bay 13) (girders-crate 103))
           (holds (bay 8) (grates-crate 100))
           (holds (bay 11) (girders-crate 102))
           (holds (shelf 16) (wheels-crate 113))
           (holds (shelf 64) (wheels-crate 95))
           (holds (bay 3) (lights-crate 120))
           (holds (shelf 34) (compressors-crate 108))
           (holds (shelf 73) (compressors-crate 114))
           (holds (shelf 59) (tyres-crate 116))
           (holds (shelf 69) (wooden-planks-crate 87))
           (holds (bay 7) (screws-crate 92))
           (holds (shelf 45) (wheels-crate 117))
           (holds (bay 13) (pistons-crate 99))
           (holds (shelf 71) (engines-crate 121))
           (adjacent (bay 11) (forklift 126))
           (holds (shelf 63) (girders-crate 105))
           (holds (shelf 30) (lights-crate 120))
           (holds (shelf 83) (jacks-crate 101))
           (holds (bay 6) (circular-saws-crate 106))
           (holds (shelf 58) (girders-crate 102))
           (holds (bay 7) (pistons-crate 98))
           (holds (shelf 18) (screws-crate 92))
           (holds (bay 5) (grates-crate 111))
           (holds (bay 9) (jacks-crate 115))
           (holds (bay 5) (pistons-crate 112))
           (holds (bay 1) (jacks-crate 101))
           (holds (bay 2) (wheels-crate 117))
           (holds (shelf 24) (lights-crate 94))
           (holds (shelf 49) (jacks-crate 91))
           (holds (shelf 47) (pistons-crate 110))
           (holds (shelf 54) (circular-saws-crate 88))
           (holds (bay 13) (screws-crate 96))
           (holds (shelf 53) (circular-saws-crate 106))
           (holds (bay 3) (circular-saws-crate 119))
           (holds (bay 4) (wooden-planks-crate 87))
           (holds (shelf 76) (lights-crate 85))
           (holds (shelf 68) (girders-crate 103))
           (holds (shelf 46) (girders-crate 90))
           (holds (bay 5) (compressors-crate 108))
           (holds (shelf 32) (circular-saws-crate 119))
           (holds (bay 10) (pistons-crate 107))
           (holds (forklift 126) (nails-crate 86))
           (holds (bay 8) (lights-crate 94))
           (holds (bay 4) (compressors-crate 114))
           (holds (bay 13) (screws-crate 93))
           (holds (bay 6) (jacks-crate 91))
           (holds (bay 7) (wheels-crate 113))
           (holds (shelf 56) (circular-saws-crate 84))
           (holds (shelf 77) (girders-crate 89))
           (holds (shelf 67) (screws-crate 93))
           (holds (shelf 20) (jacks-crate 115))
           (holds (bay 0) (girders-crate 89))
           (holds (bay 0) (lights-crate 85))
           (holds (bay 11) (circular-saws-crate 88))
           (holds (bay 2) (girders-crate 90))
           (holds (bay 10) (girders-crate 105))
           (holds (shelf 31) (compressors-crate 118))
           (holds (shelf 38) (grates-crate 111))
           (holds (bay 3) (compressors-crate 118))
           (holds (bay 13) (wheels-crate 95))
           (holds (bay 9) (compressors-crate 109))
           (holds (shelf 25) (grates-crate 100))
           (holds (bay 2) (pistons-crate 110))
           (holds (shelf 65) (pistons-crate 99))
           (holds (bay 5) (screws-crate 97))
           (holds (shelf 15) (pistons-crate 98))})

(def mock-world2 '#{(is-height 0 (shelf 1))
                           (is-height 0 (shelf 2))
                           (at bay (12 4) (shelf 194))
                           (is-height 4 (shelf 194))
                           })