(ns nl-injector)
 ;can take this in as a vector, NOT a map. Remove dupes and then put it INTO a map.


(def mock-dyn2 '#{
                         (stored-on (shelf 194) wheels-crate 240)
                         (on (6 0) (forklift 324))
                         (isa forklift (forklift 324))
                         (is-height 0 (forklift 324))
                         })

(def mock-world2 '#{(is-height 0 (shelf 1))
                           (is-height 0 (shelf 2))
                           (at bay (12 4) (shelf 194))
                           (is-height 4 (shelf 194))
                           })
(def mock-dyn '#{
                 (stored-on (shelf 53) tyres-crate 271)
                 (stored-on (shelf 49) nails-crate 272)
                 (stored-on (shelf 50) bolts-crate 280)
                 (stored-on (shelf 140) circular-saws-crate 311)
                 (stored-on (shelf 143) wheels-crate 244)
                 (stored-on (shelf 157) compressors-crate 315)
                 (stored-on (shelf 158) tyres-crate 296)
                 (stored-on (shelf 155) tyres-crate 298)
                 (stored-on (shelf 101) nails-crate 248)
                 (stored-on (shelf 174) wooden-planks-crate 247)
                 (stored-on (shelf 109) wooden-planks-crate 252)
                 (stored-on (shelf 208) tyres-crate 276)
                 (stored-on (shelf 206) pistons-crate 316)
                 (stored-on (shelf 205) wheels-crate 301)
                 (stored-on (shelf 189) compressors-crate 297)
                 (stored-on (shelf 227) girders-crate 245)
                 (stored-on (shelf 224) nails-crate 234)
                 (stored-on (shelf 226) pistons-crate 321)
                 (stored-on (shelf 93) lights-crate 282)
                 (stored-on (shelf 59) lights-crate 304)
                 (stored-on (shelf 62) nails-crate 246)
                 (stored-on (shelf 194) wheels-crate 240)
                 (stored-on (shelf 96) nails-crate 235)
                 (stored-on (shelf 95) nails-crate 303)
                 (stored-on (shelf 97) circular-saws-crate 270)
                 (stored-on (shelf 94) girders-crate 299)
                 (stored-on (shelf 179) nails-crate 249)
                 (stored-on (shelf 43) grates-crate 242)
                 (stored-on (shelf 41) compressors-crate 318)
                 (stored-on (shelf 124) nails-crate 255)
                 (stored-on (shelf 126) grates-crate 317)
                 (stored-on (shelf 125) circular-saws-crate 257)
                 (stored-on (shelf 150) nails-crate 314)
                 (stored-on (shelf 163) circular-saws-crate 243)
                 (stored-on (shelf 162) grates-crate 305)
                 (stored-on (shelf 159) bolts-crate 281)
                 (stored-on (shelf 160) grates-crate 313)
                 (stored-on (shelf 55) girders-crate 293)
                 (stored-on (shelf 54) nails-crate 260)
                 (stored-on (shelf 57) lights-crate 302)
                 (stored-on (shelf 56) girders-crate 253)
                 (stored-on (shelf 186) circular-saws-crate 306)
                 (stored-on (shelf 134) grates-crate 294)
                 (stored-on (shelf 106) pistons-crate 239)
                 (stored-on (shelf 105) girders-crate 300)
                 (stored-on (shelf 107) screws-crate 269)
                 (stored-on (shelf 231) bolts-crate 308)
                 (stored-on (shelf 229) wheels-crate 263)
                 (stored-on (shelf 81) pistons-crate 320)
                 (stored-on (shelf 80) bolts-crate 295)
                 (stored-on (shelf 82) grates-crate 236)
                 (stored-on (shelf 117) tyres-crate 241)
                 (stored-on (shelf 116) nails-crate 310)
                 (stored-on (shelf 115) lights-crate 266)
                 (stored-on (shelf 45) wooden-planks-crate 278)
                 (stored-on (shelf 48) lights-crate 267)
                 (stored-on (shelf 47) wheels-crate 290)
                 (stored-on (shelf 147) wheels-crate 291)
                 (stored-on (shelf 148) grates-crate 238)
                 (stored-on (shelf 145) circular-saws-crate 261)
                 (stored-on (shelf 144) screws-crate 262)
                 (stored-on (shelf 213) compressors-crate 259)
                 (stored-on (shelf 212) compressors-crate 286)
                 (stored-on (shelf 72) pistons-crate 312)
                 (stored-on (shelf 70) lights-crate 283)
                 (stored-on (shelf 67) engines-crate 287)
                 (stored-on (shelf 66) compressors-crate 277)
                 (stored-on (shelf 222) grates-crate 274)
                 (stored-on (shelf 223) tyres-crate 323)
                 (stored-on (shelf 220) pistons-crate 250)
                 (stored-on (shelf 119) engines-crate 309)
                 (stored-on (shelf 120) engines-crate 279)
                 (stored-on (shelf 122) circular-saws-crate 288)
                 (stored-on (shelf 173) screws-crate 322)
                 (stored-on (shelf 171) bolts-crate 307)
                 (stored-on (shelf 214) wooden-planks-crate 264)
                 (stored-on (shelf 216) wooden-planks-crate 237)
                 (stored-on (shelf 217) pistons-crate 254)
                 (stored-on (shelf 218) screws-crate 268)
                 (stored-on (shelf 86) wooden-planks-crate 273)
                 (stored-on (shelf 88) wheels-crate 275)
                 (stored-on (shelf 87) lights-crate 256)
                 (stored-on (shelf 84) wooden-planks-crate 258)
                 (stored-on (shelf 201) circular-saws-crate 292)
                 (stored-on (shelf 200) tyres-crate 319)
                 (stored-on (shelf 164) pistons-crate 289)
                 (stored-on (shelf 165) girders-crate 285)
                 (stored-on (shelf 166) engines-crate 284)
                 (stored-on (shelf 167) wooden-planks-crate 265)
                 (on (6 0) (forklift 324))
                 (isa forklift (forklift 324))
                 (is-height 0 (forklift 324))
                 (stored-on (shelf 131) tyres-crate 251) ; (stored-on (shelf ?s) ?object ?o)
                 })

; TODO: ADD IS A FORKLIFT IN NL, ITS CURRENTLY IN DYN STATE
=(def mock-world '#{
                    (adjacent bay (8 7) patch (7 7))
                    (adjacent bay (8 7) patch (9 7))
                    (at bay (8 7) (shelf 91))
                    (is-height 3 (shelf 91))
                    (at bay (8 7) (shelf 89))
                    (is-height 2 (shelf 89))
                    (at bay (8 7) (shelf 92))
                    (is-height 4 (shelf 92))
                    (at bay (8 7) (shelf 93))
                    (is-height 1 (shelf 93))
                    (at bay (8 7) (shelf 90))
                    (is-height 0 (shelf 90))
                    (adjacent bay (12 2) patch (11 2))
                    (adjacent bay (12 2) patch (13 2))
                    (at bay (12 2) (shelf 225))
                    (is-height 1 (shelf 225))
                    (at bay (12 2) (shelf 228))
                    (is-height 4 (shelf 228))
                    (at bay (12 2) (shelf 224))
                    (is-height 2 (shelf 224))
                    (at bay (12 2) (shelf 227))
                    (is-height 0 (shelf 227))
                    (at bay (12 2) (shelf 226))
                    (is-height 3 (shelf 226))
                    (adjacent bay (4 3) patch (3 3))
                    (adjacent bay (4 3) patch (5 3))
                    (at bay (4 3) (shelf 190))
                    (is-height 0 (shelf 190))
                    (at bay (4 3) (shelf 193))
                    (is-height 2 (shelf 193))
                    (at bay (4 3) (shelf 192))
                    (is-height 3 (shelf 192))
                    (at bay (4 3) (shelf 191))
                    (is-height 4 (shelf 191))
                    (at bay (4 3) (shelf 189))
                    (is-height 1 (shelf 189))
                    (adjacent bay (8 9) patch (7 9))
                    (adjacent bay (8 9) patch (9 9))
                    (at bay (8 9) (shelf 94))
                    (is-height 1 (shelf 94))
                    (at bay (8 9) (shelf 98))
                    (is-height 3 (shelf 98))
                    (at bay (8 9) (shelf 96))
                    (is-height 2 (shelf 96))
                    (at bay (8 9) (shelf 97))
                    (is-height 4 (shelf 97))
                    (at bay (8 9) (shelf 95))
                    (is-height 0 (shelf 95))
                    (adjacent bay (12 10) patch (11 10))
                    (adjacent bay (12 10) patch (13 10))
                    (at bay (12 10) (shelf 209))
                    (is-height 0 (shelf 209))
                    (at bay (12 10) (shelf 210))
                    (is-height 2 (shelf 210))
                    (at bay (12 10) (shelf 211))
                    (is-height 3 (shelf 211))
                    (at bay (12 10) (shelf 213))
                    (is-height 1 (shelf 213))
                    (at bay (12 10) (shelf 212))
                    (is-height 4 (shelf 212))
                    (adjacent bay (8 4) patch (7 4))
                    (adjacent bay (8 4) patch (9 4))
                    (at bay (8 4) (shelf 206))
                    (is-height 4 (shelf 206))
                    (at bay (8 4) (shelf 204))
                    (is-height 2 (shelf 204))
                    (at bay (8 4) (shelf 208))
                    (is-height 1 (shelf 208))
                    (at bay (8 4) (shelf 205))
                    (is-height 0 (shelf 205))
                    (at bay (8 4) (shelf 207))
                    (is-height 3 (shelf 207))
                    (adjacent bay (12 3) patch (11 3))
                    (adjacent bay (12 3) patch (13 3))
                    (at bay (12 3) (shelf 214))
                    (is-height 0 (shelf 214))
                    (at bay (12 3) (shelf 218))
                    (is-height 3 (shelf 218))
                    (at bay (12 3) (shelf 217))
                    (is-height 1 (shelf 217))
                    (at bay (12 3) (shelf 215))
                    (is-height 4 (shelf 215))
                    (at bay (12 3) (shelf 216))
                    (is-height 2 (shelf 216))
                    (adjacent bay (8 5) patch (7 5))
                    (adjacent bay (8 5) patch (9 5))
                    (at bay (8 5) (shelf 101))
                    (is-height 0 (shelf 101))
                    (at bay (8 5) (shelf 100))
                    (is-height 4 (shelf 100))
                    (at bay (8 5) (shelf 102))
                    (is-height 3 (shelf 102))
                    (at bay (8 5) (shelf 99))
                    (is-height 2 (shelf 99))
                    (at bay (8 5) (shelf 103))
                    (is-height 1 (shelf 103))
                    (adjacent bay (4 2) patch (3 2))
                    (adjacent bay (4 2) patch (5 2))
                    (at bay (4 2) (shelf 169))
                    (is-height 3 (shelf 169))
                    (at bay (4 2) (shelf 173))
                    (is-height 0 (shelf 173))
                    (at bay (4 2) (shelf 170))
                    (is-height 4 (shelf 170))
                    (at bay (4 2) (shelf 171))
                    (is-height 1 (shelf 171))
                    (at bay (4 2) (shelf 172))
                    (is-height 2 (shelf 172))
                    (adjacent bay (8 12) patch (7 12))
                    (adjacent bay (8 12) patch (9 12))
                    (at bay (8 12) (shelf 42))
                    (is-height 1 (shelf 42))
                    (at bay (8 12) (shelf 43))
                    (is-height 3 (shelf 43))
                    (at bay (8 12) (shelf 40))
                    (is-height 4 (shelf 40))
                    (at bay (8 12) (shelf 39))
                    (is-height 0 (shelf 39))
                    (at bay (8 12) (shelf 41))
                    (is-height 2 (shelf 41))
                    (adjacent bay (4 12) patch (3 12))
                    (adjacent bay (4 12) patch (5 12))
                    (at bay (4 12) (shelf 181))
                    (is-height 4 (shelf 181))
                    (at bay (4 12) (shelf 180))
                    (is-height 0 (shelf 180))
                    (at bay (4 12) (shelf 183))
                    (is-height 1 (shelf 183))
                    (at bay (4 12) (shelf 179))
                    (is-height 2 (shelf 179))
                    (at bay (4 12) (shelf 182))
                    (is-height 3 (shelf 182))
                    (adjacent bay (4 8) patch (3 8))
                    (adjacent bay (4 8) patch (5 8))
                    (at bay (4 8) (shelf 81))
                    (is-height 2 (shelf 81))
                    (at bay (4 8) (shelf 80))
                    (is-height 4 (shelf 80))
                    (at bay (4 8) (shelf 83))
                    (is-height 0 (shelf 83))
                    (at bay (4 8) (shelf 79))
                    (is-height 3 (shelf 79))
                    (at bay (4 8) (shelf 82))
                    (is-height 1 (shelf 82))
                    (adjacent bay (8 8) patch (7 8))
                    (adjacent bay (8 8) patch (9 8))
                    (at bay (8 8) (shelf 69))
                    (is-height 4 (shelf 69))
                    (at bay (8 8) (shelf 72))
                    (is-height 0 (shelf 72))
                    (at bay (8 8) (shelf 70))
                    (is-height 1 (shelf 70))
                    (at bay (8 8) (shelf 73))
                    (is-height 2 (shelf 73))
                    (at bay (8 8) (shelf 71))
                    (is-height 3 (shelf 71))
                    (adjacent bay (4 5) patch (3 5))
                    (adjacent bay (4 5) patch (5 5))
                    (at bay (4 5) (shelf 203))
                    (is-height 4 (shelf 203))
                    (at bay (4 5) (shelf 200))
                    (is-height 2 (shelf 200))
                    (at bay (4 5) (shelf 199))
                    (is-height 0 (shelf 199))
                    (at bay (4 5) (shelf 201))
                    (is-height 3 (shelf 201))
                    (at bay (4 5) (shelf 202))
                    (is-height 1 (shelf 202))
                    (adjacent bay (12 14) patch (11 14))
                    (adjacent bay (12 14) patch (13 14))
                    (at bay (12 14) (shelf 178))
                    (is-height 3 (shelf 178))
                    (at bay (12 14) (shelf 174))
                    (is-height 0 (shelf 174))
                    (at bay (12 14) (shelf 175))
                    (is-height 2 (shelf 175))
                    (at bay (12 14) (shelf 176))
                    (is-height 4 (shelf 176))
                    (at bay (12 14) (shelf 177))
                    (is-height 1 (shelf 177))
                    (adjacent bay (8 6) patch (7 6))
                    (adjacent bay (8 6) patch (9 6))
                    (at bay (8 6) (shelf 130))
                    (is-height 2 (shelf 130))
                    (at bay (8 6) (shelf 131))
                    (is-height 3 (shelf 131))
                    (at bay (8 6) (shelf 132))
                    (is-height 0 (shelf 132))
                    (at bay (8 6) (shelf 129))
                    (is-height 1 (shelf 129))
                    (at bay (8 6) (shelf 133))
                    (is-height 4 (shelf 133))
                    (adjacent bay (8 11) patch (7 11))
                    (adjacent bay (8 11) patch (9 11))
                    (at bay (8 11) (shelf 157))
                    (is-height 4 (shelf 157))
                    (at bay (8 11) (shelf 155))
                    (is-height 0 (shelf 155))
                    (at bay (8 11) (shelf 154))
                    (is-height 1 (shelf 154))
                    (at bay (8 11) (shelf 158))
                    (is-height 2 (shelf 158))
                    (at bay (8 11) (shelf 156))
                    (is-height 3 (shelf 156))
                    (adjacent bay (12 4) patch (11 4))
                    (adjacent bay (12 4) patch (13 4))
                    (at bay (12 4) (shelf 198))
                    (is-height 1 (shelf 198))
                    (at bay (12 4) (shelf 194))
                    (is-height 4 (shelf 194))
                    (at bay (12 4) (shelf 197))
                    (is-height 3 (shelf 197))
                    (at bay (12 4) (shelf 195))
                    (is-height 0 (shelf 195))
                    (at bay (12 4) (shelf 196))
                    (is-height 2 (shelf 196))
                    (adjacent bay (12 13) patch (11 13))
                    (adjacent bay (12 13) patch (13 13))
                    (at bay (12 13) (shelf 46))
                    (is-height 3 (shelf 46))
                    (at bay (12 13) (shelf 45))
                    (is-height 1 (shelf 45))
                    (at bay (12 13) (shelf 48))
                    (is-height 2 (shelf 48))
                    (at bay (12 13) (shelf 44))
                    (is-height 0 (shelf 44))
                    (at bay (12 13) (shelf 47))
                    (is-height 4 (shelf 47))
                    (adjacent bay (4 11) patch (3 11))
                    (adjacent bay (4 11) patch (5 11))
                    (at bay (4 11) (shelf 118))
                    (is-height 3 (shelf 118))
                    (at bay (4 11) (shelf 116))
                    (is-height 0 (shelf 116))
                    (at bay (4 11) (shelf 115))
                    (is-height 4 (shelf 115))
                    (at bay (4 11) (shelf 114))
                    (is-height 1 (shelf 114))
                    (at bay (4 11) (shelf 117))
                    (is-height 2 (shelf 117))
                    (adjacent bay (4 6) patch (3 6))
                    (adjacent bay (4 6) patch (5 6))
                    (at bay (4 6) (shelf 61))
                    (is-height 4 (shelf 61))
                    (at bay (4 6) (shelf 62))
                    (is-height 1 (shelf 62))
                    (at bay (4 6) (shelf 59))
                    (is-height 2 (shelf 59))
                    (at bay (4 6) (shelf 63))
                    (is-height 0 (shelf 63))
                    (at bay (4 6) (shelf 60))
                    (is-height 3 (shelf 60))
                    (adjacent bay (8 10) patch (7 10))
                    (adjacent bay (8 10) patch (9 10))
                    (at bay (8 10) (shelf 223))
                    (is-height 0 (shelf 223))
                    (at bay (8 10) (shelf 221))
                    (is-height 3 (shelf 221))
                    (at bay (8 10) (shelf 222))
                    (is-height 1 (shelf 222))
                    (at bay (8 10) (shelf 219))
                    (is-height 4 (shelf 219))
                    (at bay (8 10) (shelf 220))
                    (is-height 2 (shelf 220))
                    (adjacent bay (12 5) patch (11 5))
                    (adjacent bay (12 5) patch (13 5))
                    (at bay (12 5) (shelf 56))
                    (is-height 1 (shelf 56))
                    (at bay (12 5) (shelf 58))
                    (is-height 4 (shelf 58))
                    (at bay (12 5) (shelf 54))
                    (is-height 3 (shelf 54))
                    (at bay (12 5) (shelf 57))
                    (is-height 0 (shelf 57))
                    (at bay (12 5) (shelf 55))
                    (is-height 2 (shelf 55))
                    (adjacent bay (4 13) patch (3 13))
                    (adjacent bay (4 13) patch (5 13))
                    (at bay (4 13) (shelf 230))
                    (is-height 2 (shelf 230))
                    (at bay (4 13) (shelf 231))
                    (is-height 4 (shelf 231))
                    (at bay (4 13) (shelf 233))
                    (is-height 3 (shelf 233))
                    (at bay (4 13) (shelf 232))
                    (is-height 0 (shelf 232))
                    (at bay (4 13) (shelf 229))
                    (is-height 1 (shelf 229))
                    (adjacent bay (4 7) patch (3 7))
                    (adjacent bay (4 7) patch (5 7))
                    (at bay (4 7) (shelf 142))
                    (is-height 2 (shelf 142))
                    (at bay (4 7) (shelf 140))
                    (is-height 4 (shelf 140))
                    (at bay (4 7) (shelf 139))
                    (is-height 3 (shelf 139))
                    (at bay (4 7) (shelf 143))
                    (is-height 1 (shelf 143))
                    (at bay (4 7) (shelf 141))
                    (is-height 0 (shelf 141))
                    (adjacent bay (12 12) patch (11 12))
                    (adjacent bay (12 12) patch (13 12))
                    (at bay (12 12) (shelf 121))
                    (is-height 3 (shelf 121))
                    (at bay (12 12) (shelf 120))
                    (is-height 2 (shelf 120))
                    (at bay (12 12) (shelf 119))
                    (is-height 4 (shelf 119))
                    (at bay (12 12) (shelf 123))
                    (is-height 0 (shelf 123))
                    (at bay (12 12) (shelf 122))
                    (is-height 1 (shelf 122))
                    (adjacent bay (12 6) patch (11 6))
                    (adjacent bay (12 6) patch (13 6))
                    (at bay (12 6) (shelf 134))
                    (is-height 3 (shelf 134))
                    (at bay (12 6) (shelf 136))
                    (is-height 2 (shelf 136))
                    (at bay (12 6) (shelf 135))
                    (is-height 1 (shelf 135))
                    (at bay (12 6) (shelf 137))
                    (is-height 4 (shelf 137))
                    (at bay (12 6) (shelf 138))
                    (is-height 0 (shelf 138))
                    (adjacent bay (4 4) patch (3 4))
                    (adjacent bay (4 4) patch (5 4))
                    (at bay (4 4) (shelf 113))
                    (is-height 3 (shelf 113))
                    (at bay (4 4) (shelf 109))
                    (is-height 0 (shelf 109))
                    (at bay (4 4) (shelf 110))
                    (is-height 2 (shelf 110))
                    (at bay (4 4) (shelf 112))
                    (is-height 1 (shelf 112))
                    (at bay (4 4) (shelf 111))
                    (is-height 4 (shelf 111))
                    (adjacent bay (12 11) patch (11 11))
                    (adjacent bay (12 11) patch (13 11))
                    (at bay (12 11) (shelf 49))
                    (is-height 3 (shelf 49))
                    (at bay (12 11) (shelf 50))
                    (is-height 2 (shelf 50))
                    (at bay (12 11) (shelf 53))
                    (is-height 0 (shelf 53))
                    (at bay (12 11) (shelf 52))
                    (is-height 1 (shelf 52))
                    (at bay (12 11) (shelf 51))
                    (is-height 4 (shelf 51))
                    (adjacent bay (12 9) patch (11 9))
                    (adjacent bay (12 9) patch (13 9))
                    (at bay (12 9) (shelf 77))
                    (is-height 0 (shelf 77))
                    (at bay (12 9) (shelf 74))
                    (is-height 2 (shelf 74))
                    (at bay (12 9) (shelf 78))
                    (is-height 4 (shelf 78))
                    (at bay (12 9) (shelf 76))
                    (is-height 3 (shelf 76))
                    (at bay (12 9) (shelf 75))
                    (is-height 1 (shelf 75))
                    (adjacent bay (8 13) patch (7 13))
                    (adjacent bay (8 13) patch (9 13))
                    (at bay (8 13) (shelf 68))
                    (is-height 3 (shelf 68))
                    (at bay (8 13) (shelf 64))
                    (is-height 4 (shelf 64))
                    (at bay (8 13) (shelf 66))
                    (is-height 2 (shelf 66))
                    (at bay (8 13) (shelf 67))
                    (is-height 1 (shelf 67))
                    (at bay (8 13) (shelf 65))
                    (is-height 0 (shelf 65))
                    (adjacent bay (4 14) patch (3 14))
                    (adjacent bay (4 14) patch (5 14))
                    (at bay (4 14) (shelf 185))
                    (is-height 4 (shelf 185))
                    (at bay (4 14) (shelf 188))
                    (is-height 1 (shelf 188))
                    (at bay (4 14) (shelf 186))
                    (is-height 3 (shelf 186))
                    (at bay (4 14) (shelf 187))
                    (is-height 0 (shelf 187))
                    (at bay (4 14) (shelf 184))
                    (is-height 2 (shelf 184))
                    (adjacent bay (8 14) patch (7 14))
                    (adjacent bay (8 14) patch (9 14))
                    (at bay (8 14) (shelf 87))
                    (is-height 3 (shelf 87))
                    (at bay (8 14) (shelf 86))
                    (is-height 4 (shelf 86))
                    (at bay (8 14) (shelf 88))
                    (is-height 1 (shelf 88))
                    (at bay (8 14) (shelf 84))
                    (is-height 0 (shelf 84))
                    (at bay (8 14) (shelf 85))
                    (is-height 2 (shelf 85))
                    (adjacent bay (12 7) patch (11 7))
                    (adjacent bay (12 7) patch (13 7))
                    (at bay (12 7) (shelf 125))
                    (is-height 4 (shelf 125))
                    (at bay (12 7) (shelf 126))
                    (is-height 3 (shelf 126))
                    (at bay (12 7) (shelf 124))
                    (is-height 1 (shelf 124))
                    (at bay (12 7) (shelf 127))
                    (is-height 2 (shelf 127))
                    (at bay (12 7) (shelf 128))
                    (is-height 0 (shelf 128))
                    (adjacent bay (4 9) patch (3 9))
                    (adjacent bay (4 9) patch (5 9))
                    (at bay (4 9) (shelf 105))
                    (is-height 4 (shelf 105))
                    (at bay (4 9) (shelf 108))
                    (is-height 3 (shelf 108))
                    (at bay (4 9) (shelf 104))
                    (is-height 1 (shelf 104))
                    (at bay (4 9) (shelf 106))
                    (is-height 0 (shelf 106))
                    (at bay (4 9) (shelf 107))
                    (is-height 2 (shelf 107))
                    (adjacent bay (8 2) patch (7 2))
                    (adjacent bay (8 2) patch (9 2))
                    (at bay (8 2) (shelf 162))
                    (is-height 0 (shelf 162))
                    (at bay (8 2) (shelf 160))
                    (is-height 2 (shelf 160))
                    (at bay (8 2) (shelf 161))
                    (is-height 1 (shelf 161))
                    (at bay (8 2) (shelf 163))
                    (is-height 4 (shelf 163))
                    (at bay (8 2) (shelf 159))
                    (is-height 3 (shelf 159))
                    (adjacent bay (4 10) patch (3 10))
                    (adjacent bay (4 10) patch (5 10))
                    (at bay (4 10) (shelf 153))
                    (is-height 4 (shelf 153))
                    (at bay (4 10) (shelf 152))
                    (is-height 2 (shelf 152))
                    (at bay (4 10) (shelf 149))
                    (is-height 1 (shelf 149))
                    (at bay (4 10) (shelf 151))
                    (is-height 3 (shelf 151))
                    (at bay (4 10) (shelf 150))
                    (is-height 0 (shelf 150))
                    (adjacent bay (12 8) patch (11 8))
                    (adjacent bay (12 8) patch (13 8))
                    (at bay (12 8) (shelf 166))
                    (is-height 2 (shelf 166))
                    (at bay (12 8) (shelf 165))
                    (is-height 3 (shelf 165))
                    (at bay (12 8) (shelf 164))
                    (is-height 1 (shelf 164))
                    (at bay (12 8) (shelf 168))
                    (is-height 0 (shelf 168))
                    (at bay (12 8) (shelf 167))
                    (is-height 4 (shelf 167))
                    (adjacent bay (8 3) patch (7 3))
                    (adjacent bay (8 3) patch (9 3))
                    (at bay (8 3) (shelf 144))
                    (is-height 4 (shelf 144))
                    (at bay (8 3) (shelf 146))
                    (is-height 0 (shelf 146))
                    (at bay (8 3) (shelf 148))
                    (is-height 3 (shelf 148))
                    (at bay (8 3) (shelf 145))
                    (is-height 1 (shelf 145))
                    (at bay (8 3) (shelf 147))
                    (is-height 2 (shelf 147))
                  })

